# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "swag init -g cmd/main.go && go build -o main cmd/main.go"
bin = "main"
full_bin = "./main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "docs"]
delay = 1000
exclude_regex = ["_test.go"]

[log]
time = true

[color]
main = "yellow"
