basePath: /
definitions:
  dto.ChangeEmailRequest:
    properties:
      new_email:
        example: john.doe@example.com
        type: string
      otp:
        example: "000000"
        type: string
    type: object
  dto.ChangePasswordRequest:
    properties:
      email:
        example: john@example.com
        type: string
      otp:
        example: "000000"
        type: string
      password:
        example: newpassword
        type: string
    type: object
  dto.ChangePhoneRequest:
    properties:
      new_phone:
        example: "628112123123"
        type: string
      otp:
        example: "000000"
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      data:
        $ref: '#/definitions/dto.ErrorResponseData'
      status:
        example: error
        type: string
    type: object
  dto.ErrorResponseData:
    properties:
      message:
        example: invalid request body
        type: string
    type: object
  dto.LoginRequest:
    properties:
      email:
        example: arm.adrian02@gmail.com
        type: string
      password:
        example: masukaja123
        type: string
    type: object
  dto.SuccessResponse:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      status:
        example: success
        type: string
    type: object
  dto.VerifyOTPRequest:
    properties:
      email:
        example: john@example.com
        type: string
      otp:
        example: "000000"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the user service for the Byow app
  title: Build Your Own Website User Service API
  version: "1.0"
paths:
  /api/users/change-email:
    post:
      description: Change user email using OTP verification
      parameters:
      - description: OTP & New Email
        in: body
        name: otp
        required: true
        schema:
          $ref: '#/definitions/dto.ChangeEmailRequest'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Change Email With OTP
      tags:
      - Users
  /api/users/change-email/send-otp:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Send OTP Change Email
      tags:
      - Users
  /api/users/change-phone:
    post:
      description: Change user phone using OTP verification
      parameters:
      - description: OTP & New Email
        in: body
        name: otp
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePhoneRequest'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Change Phone With OTP Email
      tags:
      - Users
  /api/users/change-phone/send-otp:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Send OTP Change Email
      tags:
      - Users
  /api/users/logout:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Logout user
      tags:
      - Users
  /api/users/me:
    get:
      description: Check if user is logged in and return user info
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Check Logged Account
      tags:
      - Users
  /api/users/onboard:
    get:
      description: Onboard user to the system
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Onboarded User
      tags:
      - Users
  /api/users/update:
    post:
      consumes:
      - application/json
      description: Update user information
      parameters:
      - description: Full name
        example: John Doe
        in: formData
        name: full_name
        required: true
        type: string
      - description: Email
        example: john@example.com
        in: formData
        name: email
        required: true
        type: string
      - description: Avatar file
        in: formData
        name: avatar
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Update User
      tags:
      - Users
  /auth/users/change-password-otp:
    post:
      description: Change user password using OTP verification
      parameters:
      - description: Email, OTP & New Password
        in: body
        name: otp
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePasswordRequest'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Change Password With OTP
      tags:
      - Authentication
  /auth/users/forgot-password/send-otp:
    get:
      parameters:
      - description: Email address
        in: query
        name: email
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Send OTP Forgot Password
      tags:
      - Authentication
  /auth/users/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email & Password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Login user
      tags:
      - Authentication
  /auth/users/register:
    post:
      consumes:
      - multipart/form-data
      description: Register a new user with avatar
      parameters:
      - description: Full name
        example: John Doe
        in: formData
        name: full_name
        required: true
        type: string
      - description: Email
        example: john@example.com
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        example: supersecret
        in: formData
        name: password
        required: true
        type: string
      - description: Phone number
        example: "628112123123"
        in: formData
        name: phone_number
        required: true
        type: string
      - description: Avatar file
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Register user
      tags:
      - Authentication
  /verification/users/send-otp:
    get:
      parameters:
      - description: Email address
        in: query
        name: email
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Send OTP Verification
      tags:
      - Verification
  /verification/users/verify-otp:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email & OTP
        in: body
        name: otp
        required: true
        schema:
          $ref: '#/definitions/dto.VerifyOTPRequest'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Verify OTP
      tags:
      - Verification
schemes:
- http
swagger: "2.0"
